// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4_10L1HPzOj2rQA0BekeQVenAGBYehzQ',
    appId: '1:1018710438594:web:4f314ff65f698d6c0fc15b',
    messagingSenderId: '1018710438594',
    projectId: 'flutter-live-score-app',
    authDomain: 'flutter-live-score-app.firebaseapp.com',
    storageBucket: 'flutter-live-score-app.firebasestorage.app',
    measurementId: 'G-WWVC1W60ML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa9SxEcQRnkR4C-uIOWtnC_WlUBqiHADo',
    appId: '1:1018710438594:android:cddc4e802a624f7d0fc15b',
    messagingSenderId: '1018710438594',
    projectId: 'flutter-live-score-app',
    storageBucket: 'flutter-live-score-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe55P-tInb5qHXWONg7lVnAgq1mH_2QQg',
    appId: '1:1018710438594:ios:b61058d814bb5a0c0fc15b',
    messagingSenderId: '1018710438594',
    projectId: 'flutter-live-score-app',
    storageBucket: 'flutter-live-score-app.firebasestorage.app',
    iosBundleId: 'com.examweek5.ostadAssignmentOnExamWeek5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe55P-tInb5qHXWONg7lVnAgq1mH_2QQg',
    appId: '1:1018710438594:ios:b61058d814bb5a0c0fc15b',
    messagingSenderId: '1018710438594',
    projectId: 'flutter-live-score-app',
    storageBucket: 'flutter-live-score-app.firebasestorage.app',
    iosBundleId: 'com.examweek5.ostadAssignmentOnExamWeek5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4_10L1HPzOj2rQA0BekeQVenAGBYehzQ',
    appId: '1:1018710438594:web:95036552532ba6c00fc15b',
    messagingSenderId: '1018710438594',
    projectId: 'flutter-live-score-app',
    authDomain: 'flutter-live-score-app.firebaseapp.com',
    storageBucket: 'flutter-live-score-app.firebasestorage.app',
    measurementId: 'G-5TVYHDSD9F',
  );
}
